# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2131a0c61240e3872d48b9b139ecf7c107c3a74e2ede93ea413420f8c468780e70e2e6cba699ea1bbb9a314a08b7413820a6ddae40d13efac1c0829dc53ecfcf

test:
  secret_key_base: 3a5e12eb11ae3dbd21ca81c8151ddea0e932cd03b072211779d13096aa6a511034c5546ed614f1b1980e8a88d88ad5842a0063e4c2a561363ddd2bf79d2fd20c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
